server:
  port: 9200

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ___client-id___
            client-secret: ___client-secret___
            scope: profile, email

upload:
  pictures:
    dirName: picture
    uploadPath: file:${upload.pictures.dirName}
    anonymousPicture: classpath:/images/anonymous.png
    defaultProductPicture: classpath:/images/cube.png

