server:
  port: 9200

logging:
  level:
    org.springframework.web: DEBUG

spring:
  thymeleaf:
    cache: false

upload:
  pictures:
    dirName: picture
    uploadPath: file:${upload.pictures.dirName}
    anonymousPicture: classpath:/images/anonymous.png
    defaultProductPicture: classpath:/images/cube.png